name: 每日签到

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 发送签到请求
      run: |
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.RAINYUN_API_KEY }}" \
          -d '{"task_name": "每日签到"}' \
          https://api.v2.rainyun.com/user/reward/tasks

    - name: 解析 JSON 并存储结果
      run: |
        apt update
        apt install jq
        output=$(echo ${{ steps.send-request.outputs.response }} | jq -r '.message')

    - name: 输出结果
      run: echo "接口返回：$output"
