name: 每日签到

on:
  schedule:
    # 每天10:03执行任务
    - cron: '3 10 * * *'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 签到前延迟1-2秒
      run: |
        PRE_DELAY=$((1 + RANDOM % 2))  # 1到2秒的随机延迟
        echo "签到前等待 $PRE_DELAY 秒..."
        sleep $PRE_DELAY

    - name: 发送签到请求
      run: |
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.RAINYUN_API_KEY }}" \
          -d '{"task_name": "每日签到"}' \
          https://api.v2.rainyun.com/user/reward/tasks

    - name: 签到后延迟2-3秒
      run: |
        POST_DELAY=$((2 + RANDOM % 2))  # 2到3秒的随机延迟
        echo "签到后等待 $POST_DELAY 秒..."
        sleep $POST_DELAY
